### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by krasi-georgiev** [thephpleague/oauth2-linkedin#1]
composer require league/oauth2-linkedin

Using version ^0.1.0 for league/oauth2-linkedin
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for league/oauth2-client 1.0.x-dev -> satisfiable by league/oauth2-client[1.0.x-dev].
    - league/oauth2-linkedin 0.1.0 requires league/oauth2-client 0.10.0 -> satisfiable by league/oauth2-client[0.10.0].
    - Can only install one of: league/oauth2-client[0.10.0, 1.0.x-dev].
    - Installation request for league/oauth2-linkedin ^0.1.0 -> satisfiable by league/oauth2-linkedin[0.1.0].

Installation failed, reverting ./composer.json to its original content.

when i run it with :
composer require league/oauth2-linkedin:master-dev

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for league/oauth2-linkedin master-dev -> satisfiable by league/oauth2-linkedin[dev-master].
    - league/oauth2-linkedin dev-master requires league/oauth2-client 1.0.0-beta1 -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

what am i doing wrong ?

**Comment by stevenmaguire** [comment]
Resolved in stevenmaguire/oauth2-microsoft/issues/2
