### ISSUE TITLE
This resource is no longer available under v1 APIs

### ISSUE THREAD

**Issue by damianociarla** [thephpleague/oauth2-linkedin#14]
When I invoke the "getResourceOwner" function I get this message:
`This resource is no longer available under v1 APIs`

Is it possible to update the call using the v2 apis?
I found this: [https://developer.linkedin.com/docs/guide/v2/people/profile](https://developer.linkedin.com/docs/guide/v2/people/profile-api#me)

Thanks :-)

**Comment by stevenmaguire** [comment]
@damianociarla thanks for bringing this up! It appears to be a legit issue. I will look into updating the API version ASAP.

**Comment by stevenmaguire** [comment]
@damianociarla take a look at version 4.0.0 of this package. Let me know if it does not work for you.

**Comment by stevenmaguire** [comment]
For @damianociarla and anyone else who finds this issue, I have been doing some testing with the new API and it appears as if Linkedin has begun enforcing tighter access controls. 

https://github.com/thephpleague/oauth2-linkedin#before-you-begin

If you have a different experience or feel that some alternate configuration of this package may enable obtaining resource owner information, please bring it up here.

**Comment by stevenmaguire** [comment]
I was able to access the v1 endpoint with an access token configured with the appropriate scopes and it did return results, although the results were limited when considering the explicit fields I requested. So, perhaps mileage may vary? I will update the package to allow for configuration of which endpoint you'd like to use so you at least have the flexibility to test things out for yourself.

**Comment by damianociarla** [comment]
Great! it works perfectly! I really like how you structured the code!

Thanks a lot for the timely update :-)

**Comment by Yamakasi** [comment]
I'm also/still running into this, even with a new created V2 App.

Any idea ?

**Comment by rishiraj824** [comment]
The [documentation](https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api) now recommends calling `/v2/me` for getting the details.

**Comment by Daniyaldehleh** [comment]
Hi all!
Does anyone know whether LinkedIn still allows POST message and connection request API calls? even though the [documentation](https://developer.linkedin.com/docs/v1/communications/messaging-between-connections-api) for it still exist @stevenmaguire
