### ISSUE TITLE
Using the example code results in 401 from LinkedIn

### ISSUE THREAD

**Issue by bweston92** [thephpleague/oauth2-linkedin#2]
Using the example code results in 401 from LinkedIn on the `getAccessToken` method. The code is correctly sent.

**Comment by stevenmaguire** [comment]
@bweston92 what was the story here? I assume you resolved the issue? If so, could you share the "post mortem" in case someone else encounters a similar issue?

**Comment by bweston92** [comment]
I actually had my key duplicated in key-store. Sorry guys.
