### ISSUE TITLE
Permission issues with this lib, no issues on postman with token from lib

### ISSUE THREAD

**Issue by AntonioCS** [thephpleague/oauth2-linkedin#20]
Hey guys,
I have the following code:
```
         try {
      
                var_dump($token);

                $member = $linkedinClient
                  ->getResourceOwner($token);

                var_dump($member);

            } catch (Exception $e) {
                exit('Oh dear...');
            }
```

On the var_dump of  `$member` I get the following:
```
 ["expires":protected]=> int(1541148204) ["refreshToken":protected]=> NULL ["resourceOwnerId":protected]=> NULL ["values":protected]=> array(0) { } } object(League\OAuth2\Client\Provider\LinkedInResourceOwner)#4739 (2) { ["response":protected]=> array(3) { ["serviceErrorCode"]=> int(100) ["message"]=> string(62) "not enough permissions to access field picture-url for GET /me" ["status"]=> int(403) } ["resourceOwnerId":protected]=> NULL } 
```

If I take the var_dump of `$token` and use Postman to make a request to `https://api.linkedin.com/v2/me` I get a json response with all the data, with NO ERRORS, NO PERMISSION DENIED

So I do have access to get all the information (using r_basicprofile) but for some reason via the lib I get an access denied.

What exactly am I doing wrong here?
I am using v2 of the API on PHP 7.0.28-0ubuntu0.16.04.1

**Comment by AntonioCS** [comment]
By doing doing a var_dump of `getResourceOwnerDetailsUrl` in `fetchResourceOwnerDetails` I get:
```
"https://api.linkedin.com/v2/me?fields=id,email-address,first-name,last-name,headline,location,industry,picture-url,public-profile-url,summary
```
I can see that this is coming from [here](https://github.com/thephpleague/oauth2-linkedin/blob/master/src/Provider/LinkedIn.php#L100) so it seems there is no way of just asking for the URL `https://api.linkedin.com/v2/me`

**Comment by AntonioCS** [comment]
It seems this is a field issue. If I use `firstName` instead of `first-name` it works.
This isn't mentioned anywhere in the Linkedin documentation that is linked in the fields section of your README.... so I blame this on Linkedin

**Comment by stevenmaguire** [comment]
Package version [5.0.0](https://github.com/thephpleague/oauth2-linkedin/releases/tag/5.0.0) is now available with exclusive support for LinkedInAPI v2. As @AntonioCS points out, there will be issues in pulling data from LinkedIn's API if the correct fields are not provided. The new package version removes support (and documentation) for LinkedIn API v1.
