### ISSUE TITLE
Missing refresh_token_expires_in

### ISSUE THREAD

**Issue by AntonioCS** [thephpleague/oauth2-linkedin#21]
Hey,

I have created a ticket with oauth2 lib: https://github.com/thephpleague/oauth2-client/issues/733
But maybe this will be better done here.
You can create your own AccessToken and add the missing field

**Comment by stevenmaguire** [comment]
Package version [5.0.1](https://github.com/thephpleague/oauth2-linkedin/releases/tag/5.0.1) no includes support for accessing refresh_token_expires_in as well as supporting documentation: https://github.com/thephpleague/oauth2-linkedin#refresh-tokens
