### ISSUE TITLE
Unable to retrieve access token

### ISSUE THREAD

**Issue by picks44** [thephpleague/oauth2-linkedin#27]
Hi, 

For some reason my code is not working anymore, the function `$provider->getAccessToken()` is now raising this error :

`Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists`

I've check my LinkedIn config and everything is fine. Everything was working fine until now, and we made zero changes... Any clue?

**Comment by picks44** [comment]
I've tried to use v2 of the API using 
```
$provider->withResourceOwnerVersion(2)->getAccessToken('authorization_code', [
            'code' => $code
        ]);
```

But I still get the same error

**Comment by stevenmaguire** [comment]
Package version [5.0.0](https://github.com/thephpleague/oauth2-linkedin/releases/tag/5.0.0) is now available with exclusive support for LinkedInAPI v2. I believe this will help to resolve the issues.

**Comment by picks44** [comment]
Hi @stevenmaguire, I still get the same error event with the package updated to 5.0. Again, no code update was made on your side, nor have we updated our LinkedIn config...

**Comment by picks44** [comment]
Thanks @stevenmaguire, it's fine now!
