### ISSUE TITLE
Please update library to V2 API version

### ISSUE THREAD

**Issue by Yamakasi** [thephpleague/oauth2-linkedin#28]
Hi Guys,

This library really needs the update to the V2 API.

LinkedIn.php

```
- $defaultScopes = ['r_liteprofile', 'r_emailaddress' 'w_member_social'];
- $fields = ['id', 'firstName', 'lastName', 'profilePicture'];
- $resourceOwnerVersion = 2;
```

Thanks!

**Comment by picks44** [comment]
+1

**Comment by EtienneDion** [comment]
+1

**Comment by stevenmaguire** [comment]
Package version [5.0.0](https://github.com/thephpleague/oauth2-linkedin/releases/tag/5.0.0) is now available with exclusive support for LinkedInAPI v2.
