### ISSUE TITLE
Undefined index: message on error response

### ISSUE THREAD

**Issue by Addvilz** [thephpleague/oauth2-linkedin#37]
When an error occurs, the error message seems not always present in response data. This triggers notice level error `Undefined index: message` in `\League\OAuth2\Client\Provider\LinkedIn::checkResponse` line `$data['message'] ?: $response->getReasonPhrase()`.

Small but annoying bug. Want a PR?

**Comment by stevenmaguire** [comment]
PR sounds good. Please make sure tests cover the use case. Thanks!

**Comment by Addvilz** [comment]
@stevenmaguire somehow this issue fell through the cracks of time. PR is open.
