### ISSUE TITLE
How do I access "current positions"?

### ISSUE THREAD

**Issue by rkorebrits** [thephpleague/oauth2-linkedin#9]
When authorising, I get this overview:

    *** would like to access some of your LinkedIn info:
    YOUR PROFILE OVERVIEW
    Name, photo, headline, and current positions

How do I get the current positions in the code?

**Comment by yurtesen** [comment]
I made a new pull request for that. Hopefully authors would approve. See: https://github.com/thephpleague/oauth2-linkedin/pull/10

Remember that basic access only give last position.

**Comment by stevenmaguire** [comment]
Thanks for the question and the PR. Apologies for taking so long to respond.

I have just cut a new version of this package which includes two new methods that should help you accomplish your goal while keeping a relatively small code footprint. The changes include one breaking change for BC so I've bumped the major version number. Please upgrade your composer.json file to use 3.0.0 and review this documentation: https://github.com/thephpleague/oauth2-linkedin#retrieving-linkedin-member-information

@yurtesen Thank you very much for the PR! I really appreciate your efforts there and for addressing the questions here. I will not be accepting the changes in whole for a couple of reasons, which I will explain in the PR itself.
